{{- if .Values.route.enabled }}
---
# OpenShift Route - Exposes the service externally
# This is OpenShift-specific (NOT Kubernetes Ingress)
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "account-service.fullname" . }}
  labels:
    {{- include "account-service.labels" . | nindent 4 }}
  annotations:
    # Enable HSTS for security
    haproxy.router.openshift.io/hsts_header: "max-age=31536000;includeSubDomains;preload"
spec:
  {{- if .Values.route.host }}
  host: {{ .Values.route.host }}
  {{- end }}
  {{- if .Values.route.path }}
  path: {{ .Values.route.path }}
  {{- end }}
  to:
    kind: Service
    name: {{ include "account-service.fullname" . }}
    weight: 100
  port:
    targetPort: http
  {{- if .Values.route.tls.enabled }}
  tls:
    # Edge termination - TLS terminates at the router
    termination: {{ .Values.route.tls.termination }}
    # Redirect HTTP to HTTPS
    insecureEdgeTerminationPolicy: {{ .Values.route.tls.insecureEdgeTerminationPolicy }}
  {{- end }}
  wildcardPolicy: None
{{- end }}
